import React from 'react';
import { Analytics } from '@vercel/analytics/react';
import './App.css';

function App() {
  return (
    <>
      <div className="App">
        {/* HEADER */}
        <header className="header">
          <div className="logo">NEXTORA</div>
          <nav className="nav">
            <a href="#services" className="nav-link">Services</a>
            <a href="#pricing" className="nav-link">Pricing</a>
            <a href="#contact" className="nav-link">Contact</a>
            <a href="https://t.me/nextora_bot" className="btn-primary">Start with AI</a>
          </nav>
        </header>

        {/* HERO */}
        <section className="hero">
          <h1>AI & Digital Solutions for the Next Era</h1>
          <p>We build AI bots, websites, and automation systems that scale your business.</p>
          <div className="hero-buttons">
            <a href="https://t.me/nextora_bot" className="btn-primary">Start with AI</a>
            <a href="#services" className="btn-secondary">View Services</a>
          </div>
        </section>

        {/* SERVICES */}
        <section id="services" className="services">
          <h2>Our Services</h2>
          <div className="services-grid">
            <div className="service-card">
              <div className="service-icon">🤖</div>
              <h3>AI Bots</h3>
              <p>Telegram & web bots powered by AI for business, content, and automation.</p>
            </div>
            <div className="service-card">
              <div className="service-icon">🌐</div>
              <h3>Websites</h3>
              <p>Modern, fast, conversion-focused websites with AI integration.</p>
            </div>
            <div className="service-card">
              <div className="service-icon">⚙️</div>
              <h3>Automation</h3>
              <p>Automate sales, support, and workflows using smart AI systems.</p>
            </div>
            <div className="service-card">
              <div className="service-icon">🎥</div>
              <h3>AI Content</h3>
              <p>Reels scripts, ads, captions, and visuals generated by AI.</p>
            </div>
          </div>
        </section>

        {/* WHY NEXTORA */}
        <section className="why-section">
          <h2>Why Choose Nextora</h2>
          <div className="why-grid">
            <div className="why-card">⚡ Fast delivery</div>
            <div className="why-card">🧠 AI-first approach</div>
            <div className="why-card">💎 Premium quality</div>
            <div className="why-card">🌍 Global-ready solutions</div>
          </div>
          <p>Nextora is not just a service — it's a system for building the future.</p>
        </section>

        {/* PRICING */}
        <section id="pricing" className="pricing">
          <h2>Pricing Plans</h2>
          <div className="pricing-grid">
            <div className="pricing-card">
              <h3>Starter</h3>
              <p>AI Bot basic + Landing page</p>
              <div className="price">$99</div>
              <a href="https://t.me/nextora_bot" className="btn-primary">Start Now</a>
            </div>
            <div className="pricing-card">
              <h3>Pro</h3>
              <p>AI Bot + Website + Automation</p>
              <div className="price">$299</div>
              <a href="https://t.me/nextora_bot" className="btn-primary">Start Now</a>
            </div>
            <div className="pricing-card">
              <h3>Business</h3>
              <p>Full system + Custom AI + Priority support</p>
              <div className="price">Custom</div>
              <a href="https://t.me/nextora_bot" className="btn-primary">Start Now</a>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="cta">
          <h2>Ready to build with AI?</h2>
          <a href="https://t.me/nextora_bot" className="btn-primary">Start Now</a>
        </section>

        {/* FOOTER */}
        <footer className="footer">
          <p>© 2026 Nextora</p>
          <div className="footer-links">
            <a href="https://t.me/nextora_bot">Telegram</a>
            <a href="https://instagram.com/nextora">Instagram</a>
            <a href="mailto:info@nextora.al">Email</a>
          </div>
        </footer>
      </div>
      <Analytics />
    </>
  );
}

export default App;
